### ISSUE TITLE
父组件如何改变子组件样式

### ISSUE THREAD

**Issue by okbexx** [fjc0k/vue-css-modules#1]
在vue中，父组件中使用了css module，但是子组件是第三方库，请问这时候怎么改变子组件的样式呢。

**Comment by fjc0k** [comment]
css module 语法 `:global` 就是处理这种问题的：

```css
.parent :global(.child) {
  color: red;
}
```

上面的代码大概会被编译为：

```css
.parent_d3urw .child {
  color: red;
}
```
